// Code generated by go run ./tools/generate-operations; DO NOT EDIT.
package aimodel

import "xy200303/go-newapi-sdk/newapi/core"

type Service struct {
	client        *core.Client
	Audio         *AudioService
	Chat          *ChatService
	Completions   *CompletionsService
	Embeddings    *EmbeddingsService
	Images        *ImagesService
	Models        *ModelsService
	Moderations   *ModerationsService
	Realtime      *RealtimeService
	Rerank        *RerankService
	Unimplemented *UnimplementedService
	Videos        *VideosService
}

func NewService(client *core.Client) *Service {
	return &Service{
		client:        client,
		Audio:         newAudioService(client),
		Chat:          newChatService(client),
		Completions:   newCompletionsService(client),
		Embeddings:    newEmbeddingsService(client),
		Images:        newImagesService(client),
		Models:        newModelsService(client),
		Moderations:   newModerationsService(client),
		Realtime:      newRealtimeService(client),
		Rerank:        newRerankService(client),
		Unimplemented: newUnimplementedService(client),
		Videos:        newVideosService(client),
	}
}

type AudioService struct {
	client                         *core.Client
	OpenAI                         *AudioOpenAIService
	GeminiRelayV1Beta383836364Post *core.Operation
}

func newAudioService(client *core.Client) *AudioService {
	return &AudioService{
		client:                         client,
		OpenAI:                         newAudioOpenAIService(client),
		GeminiRelayV1Beta383836364Post: core.NewOperation(client, "GeminiRelayV1Beta383836364Post", "原生Gemini格式 | New API", "POST", "/v1beta/models/{model}:generateContent", "/zh/docs/api/ai-model/audio/geminirelayv1beta-383836364"),
	}
}

type AudioOpenAIService struct {
	client                  *core.Client
	CreateSpeechPost        *core.Operation
	CreateTranscriptionPost *core.Operation
	CreateTranslationPost   *core.Operation
}

func newAudioOpenAIService(client *core.Client) *AudioOpenAIService {
	return &AudioOpenAIService{
		client:                  client,
		CreateSpeechPost:        core.NewOperation(client, "CreateSpeechPost", "文本转语音 | New API", "POST", "/v1/audio/speech", "/zh/docs/api/ai-model/audio/openai/createspeech"),
		CreateTranscriptionPost: core.NewOperation(client, "CreateTranscriptionPost", "音频转录 | New API", "POST", "/v1/audio/transcriptions", "/zh/docs/api/ai-model/audio/openai/createtranscription"),
		CreateTranslationPost:   core.NewOperation(client, "CreateTranslationPost", "音频翻译 | New API", "POST", "/v1/audio/translations", "/zh/docs/api/ai-model/audio/openai/createtranslation"),
	}
}

type ChatService struct {
	client            *core.Client
	Gemini            *ChatGeminiService
	OpenAI            *ChatOpenAIService
	CreateMessagePost *core.Operation
}

func newChatService(client *core.Client) *ChatService {
	return &ChatService{
		client:            client,
		Gemini:            newChatGeminiService(client),
		OpenAI:            newChatOpenAIService(client),
		CreateMessagePost: core.NewOperation(client, "CreateMessagePost", "原生Claude格式 | New API", "POST", "/v1/messages", "/zh/docs/api/ai-model/chat/createmessage"),
	}
}

type ChatGeminiService struct {
	client                         *core.Client
	GeminiRelayV1Beta391536411Post *core.Operation
	GeminiRelayV1BetaPost          *core.Operation
}

func newChatGeminiService(client *core.Client) *ChatGeminiService {
	return &ChatGeminiService{
		client:                         client,
		GeminiRelayV1Beta391536411Post: core.NewOperation(client, "GeminiRelayV1Beta391536411Post", "Gemini媒体识别 | New API", "POST", "/v1beta/models/{model}:generateContent", "/zh/docs/api/ai-model/chat/gemini/geminirelayv1beta-391536411"),
		GeminiRelayV1BetaPost:          core.NewOperation(client, "GeminiRelayV1BetaPost", "Gemini文本聊天 | New API", "POST", "/v1beta/models/{model}:generateContent", "/zh/docs/api/ai-model/chat/gemini/geminirelayv1beta"),
	}
}

type ChatOpenAIService struct {
	client                   *core.Client
	CreateChatCompletionPost *core.Operation
	CreateResponsePost       *core.Operation
}

func newChatOpenAIService(client *core.Client) *ChatOpenAIService {
	return &ChatOpenAIService{
		client:                   client,
		CreateChatCompletionPost: core.NewOperation(client, "CreateChatCompletionPost", "ChatCompletions格式 | New API", "POST", "/v1/chat/completions", "/zh/docs/api/ai-model/chat/openai/createchatcompletion"),
		CreateResponsePost:       core.NewOperation(client, "CreateResponsePost", "Responses格式 | New API", "POST", "/v1/responses", "/zh/docs/api/ai-model/chat/openai/createresponse"),
	}
}

type CompletionsService struct {
	client               *core.Client
	CreateCompletionPost *core.Operation
}

func newCompletionsService(client *core.Client) *CompletionsService {
	return &CompletionsService{
		client:               client,
		CreateCompletionPost: core.NewOperation(client, "CreateCompletionPost", "原生OpenAI格式 | New API", "POST", "/v1/completions", "/zh/docs/api/ai-model/completions/createcompletion"),
	}
}

type EmbeddingsService struct {
	client                    *core.Client
	CreateEmbeddingPost       *core.Operation
	CreateEngineEmbeddingPost *core.Operation
}

func newEmbeddingsService(client *core.Client) *EmbeddingsService {
	return &EmbeddingsService{
		client:                    client,
		CreateEmbeddingPost:       core.NewOperation(client, "CreateEmbeddingPost", "原生OpenAI格式 | New API", "POST", "/v1/embeddings", "/zh/docs/api/ai-model/embeddings/createembedding"),
		CreateEngineEmbeddingPost: core.NewOperation(client, "CreateEngineEmbeddingPost", "原生Gemini格式 | New API", "POST", "/v1/engines/{model}/embeddings", "/zh/docs/api/ai-model/embeddings/createengineembedding"),
	}
}

type ImagesService struct {
	client *core.Client
	Gemini *ImagesGeminiService
	OpenAI *ImagesOpenAIService
	Qwen   *ImagesQwenService
}

func newImagesService(client *core.Client) *ImagesService {
	return &ImagesService{
		client: client,
		Gemini: newImagesGeminiService(client),
		OpenAI: newImagesOpenAIService(client),
		Qwen:   newImagesQwenService(client),
	}
}

type ImagesGeminiService struct {
	client                         *core.Client
	GeminiRelayV1Beta383837589Post *core.Operation
	GeminiRelayV1Beta389846313Post *core.Operation
}

func newImagesGeminiService(client *core.Client) *ImagesGeminiService {
	return &ImagesGeminiService{
		client:                         client,
		GeminiRelayV1Beta383837589Post: core.NewOperation(client, "GeminiRelayV1Beta383837589Post", "Gemini原生格式 | New API", "POST", "/v1beta/models/{model}:generateContent/", "/zh/docs/api/ai-model/images/gemini/geminirelayv1beta-383837589"),
		GeminiRelayV1Beta389846313Post: core.NewOperation(client, "GeminiRelayV1Beta389846313Post", "OpenAI聊天格式 | New API", "POST", "/v1/chat/completions", "/zh/docs/api/ai-model/images/gemini/geminirelayv1beta-389846313"),
	}
}

type ImagesOpenAIService struct {
	client                      *core.Client
	PostV1ImagesEditsPost       *core.Operation
	PostV1ImagesGenerationSPost *core.Operation
}

func newImagesOpenAIService(client *core.Client) *ImagesOpenAIService {
	return &ImagesOpenAIService{
		client:                      client,
		PostV1ImagesEditsPost:       core.NewOperation(client, "PostV1ImagesEditsPost", "编辑图像 | New API", "POST", "/v1/images/edits/", "/zh/docs/api/ai-model/images/openai/post-v1-images-edits"),
		PostV1ImagesGenerationSPost: core.NewOperation(client, "PostV1ImagesGenerationSPost", "生成图像 | New API", "POST", "/v1/images/generations/", "/zh/docs/api/ai-model/images/openai/post-v1-images-generations"),
	}
}

type ImagesQwenService struct {
	client          *core.Client
	CreateImagePost *core.Operation
	EditimagePost   *core.Operation
}

func newImagesQwenService(client *core.Client) *ImagesQwenService {
	return &ImagesQwenService{
		client:          client,
		CreateImagePost: core.NewOperation(client, "CreateImagePost", "生成图像 | New API", "POST", "/v1/images/generations", "/zh/docs/api/ai-model/images/qwen/createimage"),
		EditimagePost:   core.NewOperation(client, "EditimagePost", "编辑图像 | New API", "POST", "/v1/images/edits", "/zh/docs/api/ai-model/images/qwen/editimage"),
	}
}

type ModelsService struct {
	client *core.Client
	List   *ModelsListService
}

func newModelsService(client *core.Client) *ModelsService {
	return &ModelsService{
		client: client,
		List:   newModelsListService(client),
	}
}

type ModelsListService struct {
	client              *core.Client
	ListmodelsGet       *core.Operation
	ListmodelsgeminiGet *core.Operation
}

func newModelsListService(client *core.Client) *ModelsListService {
	return &ModelsListService{
		client:              client,
		ListmodelsGet:       core.NewOperation(client, "ListmodelsGet", "原生OpenAI格式 | New API", "GET", "/v1/models", "/zh/docs/api/ai-model/models/list/listmodels"),
		ListmodelsgeminiGet: core.NewOperation(client, "ListmodelsgeminiGet", "原生Gemini格式 | New API", "GET", "/v1beta/models", "/zh/docs/api/ai-model/models/list/listmodelsgemini"),
	}
}

type ModerationsService struct {
	client               *core.Client
	CreateModerationPost *core.Operation
}

func newModerationsService(client *core.Client) *ModerationsService {
	return &ModerationsService{
		client:               client,
		CreateModerationPost: core.NewOperation(client, "CreateModerationPost", "原生OpenAI格式 | New API", "POST", "/v1/moderations", "/zh/docs/api/ai-model/moderations/createmoderation"),
	}
}

type RealtimeService struct {
	client                   *core.Client
	CreateRealtimeSessionGet *core.Operation
}

func newRealtimeService(client *core.Client) *RealtimeService {
	return &RealtimeService{
		client:                   client,
		CreateRealtimeSessionGet: core.NewOperation(client, "CreateRealtimeSessionGet", "原生OpenAI格式 | New API", "GET", "/v1/realtime", "/zh/docs/api/ai-model/realtime/createrealtimesession"),
	}
}

type RerankService struct {
	client           *core.Client
	CreateRerankPost *core.Operation
}

func newRerankService(client *core.Client) *RerankService {
	return &RerankService{
		client:           client,
		CreateRerankPost: core.NewOperation(client, "CreateRerankPost", "文档重排序 | New API", "POST", "/v1/rerank", "/zh/docs/api/ai-model/rerank/creatererank"),
	}
}

type UnimplementedService struct {
	client     *core.Client
	Files      *UnimplementedFilesService
	FineTuning *UnimplementedFineTuningService
}

func newUnimplementedService(client *core.Client) *UnimplementedService {
	return &UnimplementedService{
		client:     client,
		Files:      newUnimplementedFilesService(client),
		FineTuning: newUnimplementedFineTuningService(client),
	}
}

type UnimplementedFilesService struct {
	client           *core.Client
	CreateFilePost   *core.Operation
	DeleteFileDelete *core.Operation
	DownloadFileGet  *core.Operation
	ListfilesGet     *core.Operation
	RetrieveFileGet  *core.Operation
}

func newUnimplementedFilesService(client *core.Client) *UnimplementedFilesService {
	return &UnimplementedFilesService{
		client:           client,
		CreateFilePost:   core.NewOperation(client, "CreateFilePost", "上传文件 (未实现) | New API", "POST", "/v1/files", "/zh/docs/api/ai-model/unimplemented/files/createfile"),
		DeleteFileDelete: core.NewOperation(client, "DeleteFileDelete", "删除文件 (未实现) | New API", "DELETE", "/v1/files/{file_id}", "/zh/docs/api/ai-model/unimplemented/files/deletefile"),
		DownloadFileGet:  core.NewOperation(client, "DownloadFileGet", "获取文件内容 (未实现) | New API", "GET", "/v1/files/{file_id}/content", "/zh/docs/api/ai-model/unimplemented/files/downloadfile"),
		ListfilesGet:     core.NewOperation(client, "ListfilesGet", "列出文件 (未实现) | New API", "GET", "/v1/files", "/zh/docs/api/ai-model/unimplemented/files/listfiles"),
		RetrieveFileGet:  core.NewOperation(client, "RetrieveFileGet", "获取文件信息 (未实现) | New API", "GET", "/v1/files/{file_id}", "/zh/docs/api/ai-model/unimplemented/files/retrievefile"),
	}
}

type UnimplementedFineTuningService struct {
	client                *core.Client
	CancelfinetunePost    *core.Operation
	CreateFineTunePost    *core.Operation
	ListfinetuneeventsGet *core.Operation
	ListfinetunesGet      *core.Operation
	RetrieveFineTuneGet   *core.Operation
}

func newUnimplementedFineTuningService(client *core.Client) *UnimplementedFineTuningService {
	return &UnimplementedFineTuningService{
		client:                client,
		CancelfinetunePost:    core.NewOperation(client, "CancelfinetunePost", "取消微调任务 (未实现) | New API", "POST", "/v1/fine-tunes/{fine_tune_id}/cancel", "/zh/docs/api/ai-model/unimplemented/fine-tuning/cancelfinetune"),
		CreateFineTunePost:    core.NewOperation(client, "CreateFineTunePost", "创建微调任务 (未实现) | New API", "POST", "/v1/fine-tunes", "/zh/docs/api/ai-model/unimplemented/fine-tuning/createfinetune"),
		ListfinetuneeventsGet: core.NewOperation(client, "ListfinetuneeventsGet", "获取微调任务事件 (未实现) | New API", "GET", "/v1/fine-tunes/{fine_tune_id}/events", "/zh/docs/api/ai-model/unimplemented/fine-tuning/listfinetuneevents"),
		ListfinetunesGet:      core.NewOperation(client, "ListfinetunesGet", "列出微调任务 (未实现) | New API", "GET", "/v1/fine-tunes", "/zh/docs/api/ai-model/unimplemented/fine-tuning/listfinetunes"),
		RetrieveFineTuneGet:   core.NewOperation(client, "RetrieveFineTuneGet", "获取微调任务详情 (未实现) | New API", "GET", "/v1/fine-tunes/{fine_tune_id}", "/zh/docs/api/ai-model/unimplemented/fine-tuning/retrievefinetune"),
	}
}

type VideosService struct {
	client                    *core.Client
	Jimeng                    *VideosJimengService
	Kling                     *VideosKlingService
	Sora                      *VideosSoraService
	CreateVideoGenerationPost *core.Operation
	GetVideoGenerationGet     *core.Operation
}

func newVideosService(client *core.Client) *VideosService {
	return &VideosService{
		client:                    client,
		Jimeng:                    newVideosJimengService(client),
		Kling:                     newVideosKlingService(client),
		Sora:                      newVideosSoraService(client),
		CreateVideoGenerationPost: core.NewOperation(client, "CreateVideoGenerationPost", "创建视频生成任务 | New API", "POST", "/v1/video/generations", "/zh/docs/api/ai-model/videos/createvideogeneration"),
		GetVideoGenerationGet:     core.NewOperation(client, "GetVideoGenerationGet", "获取视频生成任务状态 | New API", "GET", "/v1/video/generations/{task_id}", "/zh/docs/api/ai-model/videos/getvideogeneration"),
	}
}

type VideosJimengService struct {
	client                *core.Client
	CreateJimengVideoPost *core.Operation
}

func newVideosJimengService(client *core.Client) *VideosJimengService {
	return &VideosJimengService{
		client:                client,
		CreateJimengVideoPost: core.NewOperation(client, "CreateJimengVideoPost", "即梦视频生成 | New API", "POST", "/jimeng/", "/zh/docs/api/ai-model/videos/jimeng/createjimengvideo"),
	}
}

type VideosKlingService struct {
	client                     *core.Client
	CreateKlingImage2videoPost *core.Operation
	CreateKlingText2videoPost  *core.Operation
	GetKlingImage2videoGet     *core.Operation
	GetKlingText2videoGet      *core.Operation
}

func newVideosKlingService(client *core.Client) *VideosKlingService {
	return &VideosKlingService{
		client:                     client,
		CreateKlingImage2videoPost: core.NewOperation(client, "CreateKlingImage2videoPost", "Kling 图生视频 | New API", "POST", "/kling/v1/videos/image2video", "/zh/docs/api/ai-model/videos/kling/createklingimage2video"),
		CreateKlingText2videoPost:  core.NewOperation(client, "CreateKlingText2videoPost", "Kling 文生视频 | New API", "POST", "/kling/v1/videos/text2video", "/zh/docs/api/ai-model/videos/kling/createklingtext2video"),
		GetKlingImage2videoGet:     core.NewOperation(client, "GetKlingImage2videoGet", "获取 Kling 图生视频任务状态 | New API", "GET", "/kling/v1/videos/image2video/{task_id}", "/zh/docs/api/ai-model/videos/kling/getklingimage2video"),
		GetKlingText2videoGet:      core.NewOperation(client, "GetKlingText2videoGet", "获取 Kling 文生视频任务状态 | New API", "GET", "/kling/v1/videos/text2video/{task_id}", "/zh/docs/api/ai-model/videos/kling/getklingtext2video"),
	}
}

type VideosSoraService struct {
	client             *core.Client
	CreateVideoPost    *core.Operation
	GetVideoContentGet *core.Operation
	GetVideoGet        *core.Operation
}

func newVideosSoraService(client *core.Client) *VideosSoraService {
	return &VideosSoraService{
		client:             client,
		CreateVideoPost:    core.NewOperation(client, "CreateVideoPost", "创建视频  | New API", "POST", "/v1/videos", "/zh/docs/api/ai-model/videos/sora/createvideo"),
		GetVideoContentGet: core.NewOperation(client, "GetVideoContentGet", "获取视频内容 | New API", "GET", "/v1/videos/{task_id}/content", "/zh/docs/api/ai-model/videos/sora/getvideocontent"),
		GetVideoGet:        core.NewOperation(client, "GetVideoGet", "获取视频任务状态  | New API", "GET", "/v1/videos/{task_id}", "/zh/docs/api/ai-model/videos/sora/getvideo"),
	}
}
