package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type manifestEntry struct {
	DocPath string `json:"doc_path"`
	Title   string `json:"title"`
	Method  string `json:"method"`
	Route   string `json:"route"`
}

type node struct {
	Segment  string
	Path     []string
	Children map[string]*node
	Ops      []manifestEntry
}

type packageSpec struct {
	Category string
	DirName  string
	Package  string
	RootName string
}

var packageSpecs = []packageSpec{
	{Category: "ai-model", DirName: "aimodel", Package: "aimodel", RootName: "Service"},
	{Category: "management", DirName: "management", Package: "management", RootName: "Service"},
}

var specialWords = map[string]string{
	"2fa":     "TwoFA",
	"ai":      "AI",
	"api":     "API",
	"claude":  "Claude",
	"creem":   "Creem",
	"discord": "Discord",
	"email":   "Email",
	"epay":    "EPay",
	"github":  "GitHub",
	"id":      "ID",
	"jimeng":  "Jimeng",
	"kling":   "Kling",
	"linuxdo": "LinuxDo",
	"mj":      "MJ",
	"oauth":   "OAuth",
	"oidc":    "OIDC",
	"openai":  "OpenAI",
	"qwen":    "Qwen",
	"sora":    "Sora",
	"v1":      "V1",
	"v1beta":  "V1Beta",
	"wechat":  "WeChat",
}

var knownWords = []string{
	"create", "retrieve", "download", "delete", "disable", "enable", "register", "transcription",
	"translation", "completion", "completions", "generation", "moderation", "moderations", "management", "statistics", "settings", "realtime", "response",
	"responses", "embedding", "embeddings", "agreement", "password", "passkey", "preview", "upstream",
	"payment", "pricing", "privacy", "content", "setting", "console", "balance", "channel", "channels",
	"message", "messages", "speech", "search", "models", "model", "vendor", "vendors", "backup",
	"invalid", "migrate", "default", "webhook", "telegram", "linuxdo", "github", "wechat", "stripe",
	"amount", "status", "notify", "option", "groups", "group", "ratio", "token", "tokens", "tasks",
	"task", "video", "videos", "image", "images", "audio", "rerank", "system", "login", "logout",
	"reset", "setup", "about", "notice", "policy", "self", "user", "users", "auth", "oauth", "chat",
	"verify", "state", "creem", "epay", "sync", "test", "copy", "fetch", "batch", "multi", "manage",
	"models", "stats", "stat", "data", "tags", "tag", "rest", "home", "page", "text", "file", "files",
	"fine", "tuning", "begin", "finish", "codes", "transfer", "prefill", "missing", "update",
	"post", "put", "get", "key", "topup", "aff", "relay", "gemini", "openai", "claude", "qwen",
	"jimeng", "kling", "sora", "engine", "session",
}

func main() {
	rootDir, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	manifestPath := filepath.Join(rootDir, "endpoint-manifest.json")
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		fail(err)
	}

	var entries []manifestEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		fail(err)
	}

	roots := make(map[string]*node, len(packageSpecs))
	for _, spec := range packageSpecs {
		roots[spec.Category] = &node{Children: map[string]*node{}}
	}

	for _, entry := range entries {
		if strings.TrimSpace(entry.Method) == "" || strings.TrimSpace(entry.Route) == "" {
			continue
		}

		rel := strings.TrimPrefix(entry.DocPath, "/zh/docs/api/")
		parts := strings.Split(rel, "/")
		if len(parts) < 2 {
			continue
		}

		root, ok := roots[parts[0]]
		if !ok {
			continue
		}

		current := root
		for _, part := range parts[1 : len(parts)-1] {
			if current.Children == nil {
				current.Children = map[string]*node{}
			}
			child, ok := current.Children[part]
			if !ok {
				child = &node{
					Segment:  part,
					Path:     append(append([]string{}, current.Path...), part),
					Children: map[string]*node{},
				}
				current.Children[part] = child
			}
			current = child
		}
		current.Ops = append(current.Ops, entry)
	}

	for _, spec := range packageSpecs {
		if err := writePackage(rootDir, spec, roots[spec.Category]); err != nil {
			fail(err)
		}
	}
}

func writePackage(rootDir string, spec packageSpec, root *node) error {
	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./tools/generate-operations; DO NOT EDIT.\n")
	out.WriteString("package " + spec.Package + "\n\n")
	out.WriteString("import \"github.com/xy200303/go-newapi-sdk/newapi/core\"\n\n")

	emitNode(&out, root, spec.RootName)

	outputPath := filepath.Join(rootDir, "newapi", spec.DirName, "operations_gen.go")
	return os.WriteFile(outputPath, out.Bytes(), 0644)
}

func emitNode(out *bytes.Buffer, n *node, rootName string) {
	typeName := serviceTypeName(n.Path, rootName)
	constructorName := serviceConstructorName(n.Path)

	out.WriteString(fmt.Sprintf("type %s struct {\n", typeName))
	out.WriteString("\tclient *core.Client\n")
	for _, child := range sortedChildNodes(n) {
		out.WriteString(fmt.Sprintf("\t%s *%s\n", serviceFieldName(child.Segment), serviceTypeName(child.Path, rootName)))
	}
	for _, op := range sortedOps(n.Ops) {
		out.WriteString(fmt.Sprintf("\t%s *core.Operation\n", operationFieldName(op)))
	}
	out.WriteString("}\n\n")

	out.WriteString(fmt.Sprintf("func %s(client *core.Client) *%s {\n", constructorName, typeName))
	out.WriteString(fmt.Sprintf("\treturn &%s{\n", typeName))
	out.WriteString("\t\tclient: client,\n")
	for _, child := range sortedChildNodes(n) {
		out.WriteString(fmt.Sprintf("\t\t%s: %s(client),\n", serviceFieldName(child.Segment), serviceConstructorName(child.Path)))
	}
	for _, op := range sortedOps(n.Ops) {
		fieldName := operationFieldName(op)
		out.WriteString(fmt.Sprintf("\t\t%s: core.NewOperation(client, %q, %q, %q, %q, %q),\n", fieldName, fieldName, op.Title, op.Method, op.Route, op.DocPath))
	}
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")

	for _, child := range sortedChildNodes(n) {
		emitNode(out, child, rootName)
	}
}

func serviceTypeName(path []string, rootName string) string {
	if len(path) == 0 {
		return rootName
	}

	var b strings.Builder
	for _, part := range path {
		b.WriteString(serviceFieldName(part))
	}
	b.WriteString("Service")
	return b.String()
}

func serviceConstructorName(path []string) string {
	if len(path) == 0 {
		return "NewService"
	}
	return "new" + serviceTypeName(path, "Service")
}

func serviceFieldName(segment string) string {
	return camelCase(segment)
}

func operationFieldName(entry manifestEntry) string {
	parts := strings.Split(strings.TrimPrefix(entry.DocPath, "/zh/docs/api/"), "/")
	last := parts[len(parts)-1]
	name := camelCase(last)
	method := strings.ToLower(entry.Method)
	if !strings.HasSuffix(strings.ToLower(last), method) {
		name += camelCase(method)
	}
	return name
}

func camelCase(input string) string {
	if input == "" {
		return ""
	}
	replacer := strings.NewReplacer("-", " ", "_", " ", "{", " ", "}", " ", ":", " ", ".", " ")
	parts := strings.Fields(replacer.Replace(strings.ToLower(input)))
	words := make([]string, 0, len(parts))
	for _, part := range parts {
		words = append(words, splitToken(part)...)
	}

	var b strings.Builder
	for _, word := range words {
		if mapped, ok := specialWords[word]; ok {
			b.WriteString(mapped)
			continue
		}
		if word == "" {
			continue
		}
		b.WriteString(strings.ToUpper(word[:1]))
		if len(word) > 1 {
			b.WriteString(word[1:])
		}
	}
	return b.String()
}

func splitToken(token string) []string {
	if token == "" {
		return nil
	}
	if _, ok := specialWords[token]; ok {
		return []string{token}
	}

	parts := make([]string, 0)
	rest := token
	for len(rest) > 0 {
		matched := ""
		for _, word := range knownWords {
			if strings.HasPrefix(rest, word) && len(word) > len(matched) {
				matched = word
			}
		}
		if matched == "" {
			parts = append(parts, rest)
			break
		}
		parts = append(parts, matched)
		rest = strings.TrimPrefix(rest, matched)
	}
	return parts
}

func sortedChildNodes(n *node) []*node {
	children := make([]*node, 0, len(n.Children))
	for _, child := range n.Children {
		children = append(children, child)
	}
	sort.Slice(children, func(i, j int) bool {
		return serviceFieldName(children[i].Segment) < serviceFieldName(children[j].Segment)
	})
	return children
}

func sortedOps(ops []manifestEntry) []manifestEntry {
	cloned := append([]manifestEntry(nil), ops...)
	sort.Slice(cloned, func(i, j int) bool {
		return operationFieldName(cloned[i]) < operationFieldName(cloned[j])
	})
	return cloned
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
