// Code generated by go run ./tools/generate-operations; DO NOT EDIT.
package management

import "xy200303/go-newapi-sdk/newapi/core"

type Service struct {
	client               *core.Client
	ChannelManagement    *ChannelManagementService
	Default              *DefaultService
	Groups               *GroupsService
	Logs                 *LogsService
	ModelManagement      *ModelManagementService
	OAuth                *OAuthService
	Payment              *PaymentService
	Redemption           *RedemptionService
	SecurityVerification *SecurityVerificationService
	Statistics           *StatisticsService
	System               *SystemService
	SystemSettings       *SystemSettingsService
	Tasks                *TasksService
	TokenManagement      *TokenManagementService
	TwoFactorAuth        *TwoFactorAuthService
	UserAuth             *UserAuthService
	UserManagement       *UserManagementService
	Vendors              *VendorsService
}

func NewService(client *core.Client) *Service {
	return &Service{
		client:               client,
		ChannelManagement:    newChannelManagementService(client),
		Default:              newDefaultService(client),
		Groups:               newGroupsService(client),
		Logs:                 newLogsService(client),
		ModelManagement:      newModelManagementService(client),
		OAuth:                newOAuthService(client),
		Payment:              newPaymentService(client),
		Redemption:           newRedemptionService(client),
		SecurityVerification: newSecurityVerificationService(client),
		Statistics:           newStatisticsService(client),
		System:               newSystemService(client),
		SystemSettings:       newSystemSettingsService(client),
		Tasks:                newTasksService(client),
		TokenManagement:      newTokenManagementService(client),
		TwoFactorAuth:        newTwoFactorAuthService(client),
		UserAuth:             newUserAuthService(client),
		UserManagement:       newUserManagementService(client),
		Vendors:              newVendorsService(client),
	}
}

type ChannelManagementService struct {
	client                    *core.Client
	ChannelBatchPost          *core.Operation
	ChannelBatchTagPost       *core.Operation
	ChannelCopyIDPost         *core.Operation
	ChannelDisableDDelete     *core.Operation
	ChannelFetchModelsIDGet   *core.Operation
	ChannelFetchModelsPost    *core.Operation
	ChannelFixPost            *core.Operation
	ChannelGet                *core.Operation
	ChannelIDDelete           *core.Operation
	ChannelIDGet              *core.Operation
	ChannelIDKeyPost          *core.Operation
	ChannelModelsEnableDGet   *core.Operation
	ChannelModelsGet          *core.Operation
	ChannelMultiKeyManagePost *core.Operation
	ChannelPost               *core.Operation
	ChannelPut                *core.Operation
	ChannelSearchGet          *core.Operation
	ChannelTagDisableDPost    *core.Operation
	ChannelTagEnableDPost     *core.Operation
	ChannelTagModelsGet       *core.Operation
	ChannelTagPut             *core.Operation
	ChannelTestGet            *core.Operation
	ChannelTestIDGet          *core.Operation
	ChannelUpdateBalanceGet   *core.Operation
	ChannelUpdateBalanceIDGet *core.Operation
}

func newChannelManagementService(client *core.Client) *ChannelManagementService {
	return &ChannelManagementService{
		client:                    client,
		ChannelBatchPost:          core.NewOperation(client, "ChannelBatchPost", "批量删除渠道 | New API", "POST", "/api/channel/batch", "/zh/docs/api/management/channel-management/channel-batch-post"),
		ChannelBatchTagPost:       core.NewOperation(client, "ChannelBatchTagPost", "批量设置渠道标签 | New API", "POST", "/api/channel/batch/tag", "/zh/docs/api/management/channel-management/channel-batch-tag-post"),
		ChannelCopyIDPost:         core.NewOperation(client, "ChannelCopyIDPost", "复制渠道 | New API", "POST", "/api/channel/copy/{id}", "/zh/docs/api/management/channel-management/channel-copy-id-post"),
		ChannelDisableDDelete:     core.NewOperation(client, "ChannelDisableDDelete", "删除已禁用渠道 | New API", "DELETE", "/api/channel/disabled", "/zh/docs/api/management/channel-management/channel-disabled-delete"),
		ChannelFetchModelsIDGet:   core.NewOperation(client, "ChannelFetchModelsIDGet", "获取上游模型列表 | New API", "GET", "/api/channel/fetch_models/{id}", "/zh/docs/api/management/channel-management/channel-fetch_models-id-get"),
		ChannelFetchModelsPost:    core.NewOperation(client, "ChannelFetchModelsPost", "获取模型列表 | New API", "POST", "/api/channel/fetch_models", "/zh/docs/api/management/channel-management/channel-fetch_models-post"),
		ChannelFixPost:            core.NewOperation(client, "ChannelFixPost", "修复渠道能力 | New API", "POST", "/api/channel/fix", "/zh/docs/api/management/channel-management/channel-fix-post"),
		ChannelGet:                core.NewOperation(client, "ChannelGet", "获取所有渠道 | New API", "GET", "/api/channel/", "/zh/docs/api/management/channel-management/channel-get"),
		ChannelIDDelete:           core.NewOperation(client, "ChannelIDDelete", "删除渠道 | New API", "DELETE", "/api/channel/{id}", "/zh/docs/api/management/channel-management/channel-id-delete"),
		ChannelIDGet:              core.NewOperation(client, "ChannelIDGet", "获取指定渠道 | New API", "GET", "/api/channel/{id}", "/zh/docs/api/management/channel-management/channel-id-get"),
		ChannelIDKeyPost:          core.NewOperation(client, "ChannelIDKeyPost", "获取渠道密钥 | New API", "POST", "/api/channel/{id}/key", "/zh/docs/api/management/channel-management/channel-id-key-post"),
		ChannelModelsEnableDGet:   core.NewOperation(client, "ChannelModelsEnableDGet", "获取已启用模型列表 | New API", "GET", "/api/channel/models_enabled", "/zh/docs/api/management/channel-management/channel-models_enabled-get"),
		ChannelModelsGet:          core.NewOperation(client, "ChannelModelsGet", "获取渠道模型列表 | New API", "GET", "/api/channel/models", "/zh/docs/api/management/channel-management/channel-models-get"),
		ChannelMultiKeyManagePost: core.NewOperation(client, "ChannelMultiKeyManagePost", "管理多密钥 | New API", "POST", "/api/channel/multi_key/manage", "/zh/docs/api/management/channel-management/channel-multi_key-manage-post"),
		ChannelPost:               core.NewOperation(client, "ChannelPost", "添加渠道 | New API", "POST", "/api/channel/", "/zh/docs/api/management/channel-management/channel-post"),
		ChannelPut:                core.NewOperation(client, "ChannelPut", "更新渠道 | New API", "PUT", "/api/channel/", "/zh/docs/api/management/channel-management/channel-put"),
		ChannelSearchGet:          core.NewOperation(client, "ChannelSearchGet", "搜索渠道 | New API", "GET", "/api/channel/search", "/zh/docs/api/management/channel-management/channel-search-get"),
		ChannelTagDisableDPost:    core.NewOperation(client, "ChannelTagDisableDPost", "禁用标签渠道 | New API", "POST", "/api/channel/tag/disabled", "/zh/docs/api/management/channel-management/channel-tag-disabled-post"),
		ChannelTagEnableDPost:     core.NewOperation(client, "ChannelTagEnableDPost", "启用标签渠道 | New API", "POST", "/api/channel/tag/enabled", "/zh/docs/api/management/channel-management/channel-tag-enabled-post"),
		ChannelTagModelsGet:       core.NewOperation(client, "ChannelTagModelsGet", "获取标签模型 | New API", "GET", "/api/channel/tag/models", "/zh/docs/api/management/channel-management/channel-tag-models-get"),
		ChannelTagPut:             core.NewOperation(client, "ChannelTagPut", "编辑标签渠道 | New API", "PUT", "/api/channel/tag", "/zh/docs/api/management/channel-management/channel-tag-put"),
		ChannelTestGet:            core.NewOperation(client, "ChannelTestGet", "测试所有渠道 | New API", "GET", "/api/channel/test", "/zh/docs/api/management/channel-management/channel-test-get"),
		ChannelTestIDGet:          core.NewOperation(client, "ChannelTestIDGet", "测试指定渠道 | New API", "GET", "/api/channel/test/{id}", "/zh/docs/api/management/channel-management/channel-test-id-get"),
		ChannelUpdateBalanceGet:   core.NewOperation(client, "ChannelUpdateBalanceGet", "更新所有渠道余额 | New API", "GET", "/api/channel/update_balance", "/zh/docs/api/management/channel-management/channel-update_balance-get"),
		ChannelUpdateBalanceIDGet: core.NewOperation(client, "ChannelUpdateBalanceIDGet", "更新指定渠道余额 | New API", "GET", "/api/channel/update_balance/{id}", "/zh/docs/api/management/channel-management/channel-update_balance-id-get"),
	}
}

type DefaultService struct {
	client        *core.Client
	UserTopupPost *core.Operation
}

func newDefaultService(client *core.Client) *DefaultService {
	return &DefaultService{
		client:        client,
		UserTopupPost: core.NewOperation(client, "UserTopupPost", "使用兑换码 | New API", "POST", "/api/user/topup", "/zh/docs/api/management/default/user-topup-post"),
	}
}

type GroupsService struct {
	client               *core.Client
	GroupGet             *core.Operation
	PrefillGroupGet      *core.Operation
	PrefillGroupIDDelete *core.Operation
	PrefillGroupPost     *core.Operation
	PrefillGroupPut      *core.Operation
}

func newGroupsService(client *core.Client) *GroupsService {
	return &GroupsService{
		client:               client,
		GroupGet:             core.NewOperation(client, "GroupGet", "获取所有分组 | New API", "GET", "/api/group/", "/zh/docs/api/management/groups/group-get"),
		PrefillGroupGet:      core.NewOperation(client, "PrefillGroupGet", "获取预填分组 | New API", "GET", "/api/prefill_group/", "/zh/docs/api/management/groups/prefill_group-get"),
		PrefillGroupIDDelete: core.NewOperation(client, "PrefillGroupIDDelete", "删除预填分组 | New API", "DELETE", "/api/prefill_group/{id}", "/zh/docs/api/management/groups/prefill_group-id-delete"),
		PrefillGroupPost:     core.NewOperation(client, "PrefillGroupPost", "创建预填分组 | New API", "POST", "/api/prefill_group/", "/zh/docs/api/management/groups/prefill_group-post"),
		PrefillGroupPut:      core.NewOperation(client, "PrefillGroupPut", "更新预填分组 | New API", "PUT", "/api/prefill_group/", "/zh/docs/api/management/groups/prefill_group-put"),
	}
}

type LogsService struct {
	client           *core.Client
	LogDelete        *core.Operation
	LogGet           *core.Operation
	LogSearchGet     *core.Operation
	LogSelfGet       *core.Operation
	LogSelfSearchGet *core.Operation
	LogSelfStatGet   *core.Operation
	LogStatGet       *core.Operation
	LogTokenGet      *core.Operation
}

func newLogsService(client *core.Client) *LogsService {
	return &LogsService{
		client:           client,
		LogDelete:        core.NewOperation(client, "LogDelete", "删除历史日志 | New API", "DELETE", "/api/log/", "/zh/docs/api/management/logs/log-delete"),
		LogGet:           core.NewOperation(client, "LogGet", "获取所有日志 | New API", "GET", "/api/log/", "/zh/docs/api/management/logs/log-get"),
		LogSearchGet:     core.NewOperation(client, "LogSearchGet", "搜索日志 | New API", "GET", "/api/log/search", "/zh/docs/api/management/logs/log-search-get"),
		LogSelfGet:       core.NewOperation(client, "LogSelfGet", "获取个人日志 | New API", "GET", "/api/log/self", "/zh/docs/api/management/logs/log-self-get"),
		LogSelfSearchGet: core.NewOperation(client, "LogSelfSearchGet", "搜索个人日志 | New API", "GET", "/api/log/self/search", "/zh/docs/api/management/logs/log-self-search-get"),
		LogSelfStatGet:   core.NewOperation(client, "LogSelfStatGet", "获取个人日志统计 | New API", "GET", "/api/log/self/stat", "/zh/docs/api/management/logs/log-self-stat-get"),
		LogStatGet:       core.NewOperation(client, "LogStatGet", "获取日志统计 | New API", "GET", "/api/log/stat", "/zh/docs/api/management/logs/log-stat-get"),
		LogTokenGet:      core.NewOperation(client, "LogTokenGet", "通过令牌获取日志 | New API", "GET", "/api/log/token", "/zh/docs/api/management/logs/log-token-get"),
	}
}

type ModelManagementService struct {
	client                       *core.Client
	ModelsGet                    *core.Operation
	ModelsIDDelete               *core.Operation
	ModelsIDGet                  *core.Operation
	ModelsMissingGet             *core.Operation
	ModelsPost                   *core.Operation
	ModelsPut                    *core.Operation
	ModelsSearchGet              *core.Operation
	ModelsSyncUpstreamPost       *core.Operation
	ModelsSyncUpstreamPreviewGet *core.Operation
}

func newModelManagementService(client *core.Client) *ModelManagementService {
	return &ModelManagementService{
		client:                       client,
		ModelsGet:                    core.NewOperation(client, "ModelsGet", "获取所有模型元数据 | New API", "GET", "/api/models/", "/zh/docs/api/management/model-management/models-get"),
		ModelsIDDelete:               core.NewOperation(client, "ModelsIDDelete", "删除模型 | New API", "DELETE", "/api/models/{id}", "/zh/docs/api/management/model-management/models-id-delete"),
		ModelsIDGet:                  core.NewOperation(client, "ModelsIDGet", "获取指定模型 | New API", "GET", "/api/models/{id}", "/zh/docs/api/management/model-management/models-id-get"),
		ModelsMissingGet:             core.NewOperation(client, "ModelsMissingGet", "获取缺失模型 | New API", "GET", "/api/models/missing", "/zh/docs/api/management/model-management/models-missing-get"),
		ModelsPost:                   core.NewOperation(client, "ModelsPost", "创建模型元数据 | New API", "POST", "/api/models/", "/zh/docs/api/management/model-management/models-post"),
		ModelsPut:                    core.NewOperation(client, "ModelsPut", "更新模型元数据 | New API", "PUT", "/api/models/", "/zh/docs/api/management/model-management/models-put"),
		ModelsSearchGet:              core.NewOperation(client, "ModelsSearchGet", "搜索模型 | New API", "GET", "/api/models/search", "/zh/docs/api/management/model-management/models-search-get"),
		ModelsSyncUpstreamPost:       core.NewOperation(client, "ModelsSyncUpstreamPost", "同步上游模型 | New API", "POST", "/api/models/sync_upstream", "/zh/docs/api/management/model-management/models-sync_upstream-post"),
		ModelsSyncUpstreamPreviewGet: core.NewOperation(client, "ModelsSyncUpstreamPreviewGet", "预览上游模型同步 | New API", "GET", "/api/models/sync_upstream/preview", "/zh/docs/api/management/model-management/models-sync_upstream-preview-get"),
	}
}

type OAuthService struct {
	client                *core.Client
	OAuthDiscordGet       *core.Operation
	OAuthEmailBindGet     *core.Operation
	OAuthGitHubGet        *core.Operation
	OAuthLinuxDoGet       *core.Operation
	OAuthOIDCGet          *core.Operation
	OAuthStateGet         *core.Operation
	OAuthTelegramBindGet  *core.Operation
	OAuthTelegramLoginGet *core.Operation
	OAuthWeChatBindGet    *core.Operation
	OAuthWeChatGet        *core.Operation
}

func newOAuthService(client *core.Client) *OAuthService {
	return &OAuthService{
		client:                client,
		OAuthDiscordGet:       core.NewOperation(client, "OAuthDiscordGet", "Discord OAuth登录 | New API", "GET", "/api/oauth/discord", "/zh/docs/api/management/oauth/oauth-discord-get"),
		OAuthEmailBindGet:     core.NewOperation(client, "OAuthEmailBindGet", "绑定邮箱 | New API", "GET", "/api/oauth/email/bind", "/zh/docs/api/management/oauth/oauth-email-bind-get"),
		OAuthGitHubGet:        core.NewOperation(client, "OAuthGitHubGet", "GitHub OAuth登录 | New API", "GET", "/api/oauth/github", "/zh/docs/api/management/oauth/oauth-github-get"),
		OAuthLinuxDoGet:       core.NewOperation(client, "OAuthLinuxDoGet", "LinuxDO OAuth登录 | New API", "GET", "/api/oauth/linuxdo", "/zh/docs/api/management/oauth/oauth-linuxdo-get"),
		OAuthOIDCGet:          core.NewOperation(client, "OAuthOIDCGet", "OIDC登录 | New API", "GET", "/api/oauth/oidc", "/zh/docs/api/management/oauth/oauth-oidc-get"),
		OAuthStateGet:         core.NewOperation(client, "OAuthStateGet", "生成OAuth State | New API", "GET", "/api/oauth/state", "/zh/docs/api/management/oauth/oauth-state-get"),
		OAuthTelegramBindGet:  core.NewOperation(client, "OAuthTelegramBindGet", "绑定Telegram | New API", "GET", "/api/oauth/telegram/bind", "/zh/docs/api/management/oauth/oauth-telegram-bind-get"),
		OAuthTelegramLoginGet: core.NewOperation(client, "OAuthTelegramLoginGet", "Telegram登录 | New API", "GET", "/api/oauth/telegram/login", "/zh/docs/api/management/oauth/oauth-telegram-login-get"),
		OAuthWeChatBindGet:    core.NewOperation(client, "OAuthWeChatBindGet", "绑定微信 | New API", "GET", "/api/oauth/wechat/bind", "/zh/docs/api/management/oauth/oauth-wechat-bind-get"),
		OAuthWeChatGet:        core.NewOperation(client, "OAuthWeChatGet", "微信OAuth登录 | New API", "GET", "/api/oauth/wechat", "/zh/docs/api/management/oauth/oauth-wechat-get"),
	}
}

type PaymentService struct {
	client               *core.Client
	CreemWebhookPost     *core.Operation
	StripeWebhookPost    *core.Operation
	UserAmountPost       *core.Operation
	UserCreemPayPost     *core.Operation
	UserEPayNotifyGet    *core.Operation
	UserPayPost          *core.Operation
	UserStripeAmountPost *core.Operation
	UserStripePayPost    *core.Operation
	UserTopupInfoGet     *core.Operation
	UserTopupSelfGet     *core.Operation
}

func newPaymentService(client *core.Client) *PaymentService {
	return &PaymentService{
		client:               client,
		CreemWebhookPost:     core.NewOperation(client, "CreemWebhookPost", "Creem Webhook | New API", "POST", "/api/creem/webhook", "/zh/docs/api/management/payment/creem-webhook-post"),
		StripeWebhookPost:    core.NewOperation(client, "StripeWebhookPost", "Stripe Webhook | New API", "POST", "/api/stripe/webhook", "/zh/docs/api/management/payment/stripe-webhook-post"),
		UserAmountPost:       core.NewOperation(client, "UserAmountPost", "获取支付金额 | New API", "POST", "/api/user/amount", "/zh/docs/api/management/payment/user-amount-post"),
		UserCreemPayPost:     core.NewOperation(client, "UserCreemPayPost", "发起Creem支付 | New API", "POST", "/api/user/creem/pay", "/zh/docs/api/management/payment/user-creem-pay-post"),
		UserEPayNotifyGet:    core.NewOperation(client, "UserEPayNotifyGet", "易支付回调 | New API", "GET", "/api/user/epay/notify", "/zh/docs/api/management/payment/user-epay-notify-get"),
		UserPayPost:          core.NewOperation(client, "UserPayPost", "发起易支付 | New API", "POST", "/api/user/pay", "/zh/docs/api/management/payment/user-pay-post"),
		UserStripeAmountPost: core.NewOperation(client, "UserStripeAmountPost", "获取Stripe支付金额 | New API", "POST", "/api/user/stripe/amount", "/zh/docs/api/management/payment/user-stripe-amount-post"),
		UserStripePayPost:    core.NewOperation(client, "UserStripePayPost", "发起Stripe支付 | New API", "POST", "/api/user/stripe/pay", "/zh/docs/api/management/payment/user-stripe-pay-post"),
		UserTopupInfoGet:     core.NewOperation(client, "UserTopupInfoGet", "获取充值信息 | New API", "GET", "/api/user/topup/info", "/zh/docs/api/management/payment/user-topup-info-get"),
		UserTopupSelfGet:     core.NewOperation(client, "UserTopupSelfGet", "获取用户充值记录 | New API", "GET", "/api/user/topup/self", "/zh/docs/api/management/payment/user-topup-self-get"),
	}
}

type RedemptionService struct {
	client                  *core.Client
	RedemptionGet           *core.Operation
	RedemptionIDDelete      *core.Operation
	RedemptionIDGet         *core.Operation
	RedemptionInvalidDelete *core.Operation
	RedemptionPost          *core.Operation
	RedemptionPut           *core.Operation
	RedemptionSearchGet     *core.Operation
}

func newRedemptionService(client *core.Client) *RedemptionService {
	return &RedemptionService{
		client:                  client,
		RedemptionGet:           core.NewOperation(client, "RedemptionGet", "获取所有兑换码 | New API", "GET", "/api/redemption/", "/zh/docs/api/management/redemption/redemption-get"),
		RedemptionIDDelete:      core.NewOperation(client, "RedemptionIDDelete", "删除兑换码 | New API", "DELETE", "/api/redemption/{id}", "/zh/docs/api/management/redemption/redemption-id-delete"),
		RedemptionIDGet:         core.NewOperation(client, "RedemptionIDGet", "获取指定兑换码 | New API", "GET", "/api/redemption/{id}", "/zh/docs/api/management/redemption/redemption-id-get"),
		RedemptionInvalidDelete: core.NewOperation(client, "RedemptionInvalidDelete", "删除无效兑换码 | New API", "DELETE", "/api/redemption/invalid", "/zh/docs/api/management/redemption/redemption-invalid-delete"),
		RedemptionPost:          core.NewOperation(client, "RedemptionPost", "创建兑换码 | New API", "POST", "/api/redemption/", "/zh/docs/api/management/redemption/redemption-post"),
		RedemptionPut:           core.NewOperation(client, "RedemptionPut", "更新兑换码 | New API", "PUT", "/api/redemption/", "/zh/docs/api/management/redemption/redemption-put"),
		RedemptionSearchGet:     core.NewOperation(client, "RedemptionSearchGet", "搜索兑换码 | New API", "GET", "/api/redemption/search", "/zh/docs/api/management/redemption/redemption-search-get"),
	}
}

type SecurityVerificationService struct {
	client          *core.Client
	VerifyPost      *core.Operation
	VerifyStatusGet *core.Operation
}

func newSecurityVerificationService(client *core.Client) *SecurityVerificationService {
	return &SecurityVerificationService{
		client:          client,
		VerifyPost:      core.NewOperation(client, "VerifyPost", "通用安全验证 | New API", "POST", "/api/verify", "/zh/docs/api/management/security-verification/verify-post"),
		VerifyStatusGet: core.NewOperation(client, "VerifyStatusGet", "获取验证状态 | New API", "GET", "/api/verify/status", "/zh/docs/api/management/security-verification/verify-status-get"),
	}
}

type StatisticsService struct {
	client      *core.Client
	DataGet     *core.Operation
	DataSelfGet *core.Operation
}

func newStatisticsService(client *core.Client) *StatisticsService {
	return &StatisticsService{
		client:      client,
		DataGet:     core.NewOperation(client, "DataGet", "获取所有额度数据 | New API", "GET", "/api/data/", "/zh/docs/api/management/statistics/data-get"),
		DataSelfGet: core.NewOperation(client, "DataSelfGet", "获取个人额度数据 | New API", "GET", "/api/data/self", "/zh/docs/api/management/statistics/data-self-get"),
	}
}

type SystemService struct {
	client             *core.Client
	AboutGet           *core.Operation
	HomePageContentGet *core.Operation
	ModelsGet          *core.Operation
	NoticeGet          *core.Operation
	PricingGet         *core.Operation
	PrivacyPolicyGet   *core.Operation
	RatioConfigGet     *core.Operation
	SetupGet           *core.Operation
	SetupPost          *core.Operation
	StatusGet          *core.Operation
	StatusTestGet      *core.Operation
	UptimeStatusGet    *core.Operation
	UserAgreementGet   *core.Operation
}

func newSystemService(client *core.Client) *SystemService {
	return &SystemService{
		client:             client,
		AboutGet:           core.NewOperation(client, "AboutGet", "获取关于信息 | New API", "GET", "/api/about", "/zh/docs/api/management/system/about-get"),
		HomePageContentGet: core.NewOperation(client, "HomePageContentGet", "获取首页内容 | New API", "GET", "/api/home_page_content", "/zh/docs/api/management/system/home_page_content-get"),
		ModelsGet:          core.NewOperation(client, "ModelsGet", "获取模型列表 | New API", "GET", "/api/models", "/zh/docs/api/management/system/models-get"),
		NoticeGet:          core.NewOperation(client, "NoticeGet", "获取公告 | New API", "GET", "/api/notice", "/zh/docs/api/management/system/notice-get"),
		PricingGet:         core.NewOperation(client, "PricingGet", "获取定价信息 | New API", "GET", "/api/pricing", "/zh/docs/api/management/system/pricing-get"),
		PrivacyPolicyGet:   core.NewOperation(client, "PrivacyPolicyGet", "获取隐私政策 | New API", "GET", "/api/privacy-policy", "/zh/docs/api/management/system/privacy-policy-get"),
		RatioConfigGet:     core.NewOperation(client, "RatioConfigGet", "获取倍率配置 | New API", "GET", "/api/ratio_config", "/zh/docs/api/management/system/ratio_config-get"),
		SetupGet:           core.NewOperation(client, "SetupGet", "获取初始化状态 | New API", "GET", "/api/setup", "/zh/docs/api/management/system/setup-get"),
		SetupPost:          core.NewOperation(client, "SetupPost", "初始化系统 | New API", "POST", "/api/setup", "/zh/docs/api/management/system/setup-post"),
		StatusGet:          core.NewOperation(client, "StatusGet", "获取系统状态 | New API", "GET", "/api/status", "/zh/docs/api/management/system/status-get"),
		StatusTestGet:      core.NewOperation(client, "StatusTestGet", "测试系统状态 | New API", "GET", "/api/status/test", "/zh/docs/api/management/system/status-test-get"),
		UptimeStatusGet:    core.NewOperation(client, "UptimeStatusGet", "获取Uptime Kuma状态 | New API", "GET", "/api/uptime/status", "/zh/docs/api/management/system/uptime-status-get"),
		UserAgreementGet:   core.NewOperation(client, "UserAgreementGet", "获取用户协议 | New API", "GET", "/api/user-agreement", "/zh/docs/api/management/system/user-agreement-get"),
	}
}

type SystemSettingsService struct {
	client                          *core.Client
	OptionGet                       *core.Operation
	OptionMigrateConsoleSettingPost *core.Operation
	OptionPut                       *core.Operation
	OptionRestModelRatioPost        *core.Operation
	RatioSyncChannelsGet            *core.Operation
	RatioSyncFetchPost              *core.Operation
}

func newSystemSettingsService(client *core.Client) *SystemSettingsService {
	return &SystemSettingsService{
		client:                          client,
		OptionGet:                       core.NewOperation(client, "OptionGet", "获取系统选项 | New API", "GET", "/api/option/", "/zh/docs/api/management/system-settings/option-get"),
		OptionMigrateConsoleSettingPost: core.NewOperation(client, "OptionMigrateConsoleSettingPost", "迁移控制台设置 | New API", "POST", "/api/option/migrate_console_setting", "/zh/docs/api/management/system-settings/option-migrate_console_setting-post"),
		OptionPut:                       core.NewOperation(client, "OptionPut", "更新系统选项 | New API", "PUT", "/api/option/", "/zh/docs/api/management/system-settings/option-put"),
		OptionRestModelRatioPost:        core.NewOperation(client, "OptionRestModelRatioPost", "重置模型倍率 | New API", "POST", "/api/option/rest_model_ratio", "/zh/docs/api/management/system-settings/option-rest_model_ratio-post"),
		RatioSyncChannelsGet:            core.NewOperation(client, "RatioSyncChannelsGet", "获取可同步渠道 | New API", "GET", "/api/ratio_sync/channels", "/zh/docs/api/management/system-settings/ratio_sync-channels-get"),
		RatioSyncFetchPost:              core.NewOperation(client, "RatioSyncFetchPost", "获取上游倍率 | New API", "POST", "/api/ratio_sync/fetch", "/zh/docs/api/management/system-settings/ratio_sync-fetch-post"),
	}
}

type TasksService struct {
	client      *core.Client
	MJGet       *core.Operation
	MJSelfGet   *core.Operation
	TaskGet     *core.Operation
	TaskSelfGet *core.Operation
}

func newTasksService(client *core.Client) *TasksService {
	return &TasksService{
		client:      client,
		MJGet:       core.NewOperation(client, "MJGet", "获取所有Midjourney任务 | New API", "GET", "/api/mj/", "/zh/docs/api/management/tasks/mj-get"),
		MJSelfGet:   core.NewOperation(client, "MJSelfGet", "获取个人Midjourney任务 | New API", "GET", "/api/mj/self", "/zh/docs/api/management/tasks/mj-self-get"),
		TaskGet:     core.NewOperation(client, "TaskGet", "获取所有任务 | New API", "GET", "/api/task/", "/zh/docs/api/management/tasks/task-get"),
		TaskSelfGet: core.NewOperation(client, "TaskSelfGet", "获取个人任务 | New API", "GET", "/api/task/self", "/zh/docs/api/management/tasks/task-self-get"),
	}
}

type TokenManagementService struct {
	client         *core.Client
	TokenBatchPost *core.Operation
	TokenGet       *core.Operation
	TokenIDDelete  *core.Operation
	TokenIDGet     *core.Operation
	TokenPost      *core.Operation
	TokenPut       *core.Operation
	TokenSearchGet *core.Operation
	UsageTokenGet  *core.Operation
}

func newTokenManagementService(client *core.Client) *TokenManagementService {
	return &TokenManagementService{
		client:         client,
		TokenBatchPost: core.NewOperation(client, "TokenBatchPost", "批量删除令牌 | New API", "POST", "/api/token/batch", "/zh/docs/api/management/token-management/token-batch-post"),
		TokenGet:       core.NewOperation(client, "TokenGet", "获取所有令牌 | New API", "GET", "/api/token/", "/zh/docs/api/management/token-management/token-get"),
		TokenIDDelete:  core.NewOperation(client, "TokenIDDelete", "删除令牌 | New API", "DELETE", "/api/token/{id}", "/zh/docs/api/management/token-management/token-id-delete"),
		TokenIDGet:     core.NewOperation(client, "TokenIDGet", "获取指定令牌 | New API", "GET", "/api/token/{id}", "/zh/docs/api/management/token-management/token-id-get"),
		TokenPost:      core.NewOperation(client, "TokenPost", "创建令牌 | New API", "POST", "/api/token/", "/zh/docs/api/management/token-management/token-post"),
		TokenPut:       core.NewOperation(client, "TokenPut", "更新令牌 | New API", "PUT", "/api/token/", "/zh/docs/api/management/token-management/token-put"),
		TokenSearchGet: core.NewOperation(client, "TokenSearchGet", "搜索令牌 | New API", "GET", "/api/token/search", "/zh/docs/api/management/token-management/token-search-get"),
		UsageTokenGet:  core.NewOperation(client, "UsageTokenGet", "获取令牌使用情况 | New API", "GET", "/api/usage/token/", "/zh/docs/api/management/token-management/usage-token-get"),
	}
}

type TwoFactorAuthService struct {
	client                   *core.Client
	UserTwoFABackupCodesPost *core.Operation
	UserTwoFADisablePost     *core.Operation
	UserTwoFAEnablePost      *core.Operation
	UserTwoFASetupPost       *core.Operation
	UserTwoFAStatsGet        *core.Operation
	UserTwoFAStatusGet       *core.Operation
}

func newTwoFactorAuthService(client *core.Client) *TwoFactorAuthService {
	return &TwoFactorAuthService{
		client:                   client,
		UserTwoFABackupCodesPost: core.NewOperation(client, "UserTwoFABackupCodesPost", "重新生成备用码 | New API", "POST", "/api/user/2fa/backup_codes", "/zh/docs/api/management/two-factor-auth/user-2fa-backup_codes-post"),
		UserTwoFADisablePost:     core.NewOperation(client, "UserTwoFADisablePost", "禁用2FA | New API", "POST", "/api/user/2fa/disable", "/zh/docs/api/management/two-factor-auth/user-2fa-disable-post"),
		UserTwoFAEnablePost:      core.NewOperation(client, "UserTwoFAEnablePost", "启用2FA | New API", "POST", "/api/user/2fa/enable", "/zh/docs/api/management/two-factor-auth/user-2fa-enable-post"),
		UserTwoFASetupPost:       core.NewOperation(client, "UserTwoFASetupPost", "设置2FA | New API", "POST", "/api/user/2fa/setup", "/zh/docs/api/management/two-factor-auth/user-2fa-setup-post"),
		UserTwoFAStatsGet:        core.NewOperation(client, "UserTwoFAStatsGet", "获取2FA统计 | New API", "GET", "/api/user/2fa/stats", "/zh/docs/api/management/two-factor-auth/user-2fa-stats-get"),
		UserTwoFAStatusGet:       core.NewOperation(client, "UserTwoFAStatusGet", "获取2FA状态 | New API", "GET", "/api/user/2fa/status", "/zh/docs/api/management/two-factor-auth/user-2fa-status-get"),
	}
}

type UserAuthService struct {
	client                     *core.Client
	ResetPasswordGet           *core.Operation
	UserGroupsGet              *core.Operation
	UserLoginPost              *core.Operation
	UserLoginTwoFAPost         *core.Operation
	UserLogoutGet              *core.Operation
	UserPasskeyLoginBeginPost  *core.Operation
	UserPasskeyLoginFinishPost *core.Operation
	UserRegisterPost           *core.Operation
	UserResetPost              *core.Operation
	VerificationGet            *core.Operation
}

func newUserAuthService(client *core.Client) *UserAuthService {
	return &UserAuthService{
		client:                     client,
		ResetPasswordGet:           core.NewOperation(client, "ResetPasswordGet", "发送密码重置邮件 | New API", "GET", "/api/reset_password", "/zh/docs/api/management/user-auth/reset_password-get"),
		UserGroupsGet:              core.NewOperation(client, "UserGroupsGet", "获取用户分组列表 | New API", "GET", "/api/user/groups", "/zh/docs/api/management/user-auth/user-groups-get"),
		UserLoginPost:              core.NewOperation(client, "UserLoginPost", "用户登录 | New API", "POST", "/api/user/login", "/zh/docs/api/management/user-auth/user-login-post"),
		UserLoginTwoFAPost:         core.NewOperation(client, "UserLoginTwoFAPost", "两步验证登录 | New API", "POST", "/api/user/login/2fa", "/zh/docs/api/management/user-auth/user-login-2fa-post"),
		UserLogoutGet:              core.NewOperation(client, "UserLogoutGet", "用户登出 | New API", "GET", "/api/user/logout", "/zh/docs/api/management/user-auth/user-logout-get"),
		UserPasskeyLoginBeginPost:  core.NewOperation(client, "UserPasskeyLoginBeginPost", "开始Passkey登录 | New API", "POST", "/api/user/passkey/login/begin", "/zh/docs/api/management/user-auth/user-passkey-login-begin-post"),
		UserPasskeyLoginFinishPost: core.NewOperation(client, "UserPasskeyLoginFinishPost", "完成Passkey登录 | New API", "POST", "/api/user/passkey/login/finish", "/zh/docs/api/management/user-auth/user-passkey-login-finish-post"),
		UserRegisterPost:           core.NewOperation(client, "UserRegisterPost", "用户注册 | New API", "POST", "/api/user/register", "/zh/docs/api/management/user-auth/user-register-post"),
		UserResetPost:              core.NewOperation(client, "UserResetPost", "重置密码 | New API", "POST", "/api/user/reset", "/zh/docs/api/management/user-auth/user-reset-post"),
		VerificationGet:            core.NewOperation(client, "VerificationGet", "发送邮箱验证码 | New API", "GET", "/api/verification", "/zh/docs/api/management/user-auth/verification-get"),
	}
}

type UserManagementService struct {
	client                        *core.Client
	UserAffGet                    *core.Operation
	UserAffTransferPost           *core.Operation
	UserGet                       *core.Operation
	UserIDDelete                  *core.Operation
	UserIDGet                     *core.Operation
	UserIDResetPasskeyDelete      *core.Operation
	UserIDTwoFADelete             *core.Operation
	UserManagePost                *core.Operation
	UserModelsGet                 *core.Operation
	UserPasskeyDelete             *core.Operation
	UserPasskeyGet                *core.Operation
	UserPasskeyRegisterBeginPost  *core.Operation
	UserPasskeyRegisterFinishPost *core.Operation
	UserPasskeyVerifyBeginPost    *core.Operation
	UserPasskeyVerifyFinishPost   *core.Operation
	UserPost                      *core.Operation
	UserPut                       *core.Operation
	UserSearchGet                 *core.Operation
	UserSelfDelete                *core.Operation
	UserSelfGet                   *core.Operation
	UserSelfGroupsGet             *core.Operation
	UserSelfPut                   *core.Operation
	UserSettingPut                *core.Operation
	UserTokenGet                  *core.Operation
	UserTopupCompletePost         *core.Operation
	UserTopupGet                  *core.Operation
}

func newUserManagementService(client *core.Client) *UserManagementService {
	return &UserManagementService{
		client:                        client,
		UserAffGet:                    core.NewOperation(client, "UserAffGet", "获取邀请码 | New API", "GET", "/api/user/aff", "/zh/docs/api/management/user-management/user-aff-get"),
		UserAffTransferPost:           core.NewOperation(client, "UserAffTransferPost", "转换邀请额度 | New API", "POST", "/api/user/aff_transfer", "/zh/docs/api/management/user-management/user-aff_transfer-post"),
		UserGet:                       core.NewOperation(client, "UserGet", "获取所有用户 | New API", "GET", "/api/user/", "/zh/docs/api/management/user-management/user-get"),
		UserIDDelete:                  core.NewOperation(client, "UserIDDelete", "删除用户 | New API", "DELETE", "/api/user/{id}", "/zh/docs/api/management/user-management/user-id-delete"),
		UserIDGet:                     core.NewOperation(client, "UserIDGet", "获取指定用户 | New API", "GET", "/api/user/{id}", "/zh/docs/api/management/user-management/user-id-get"),
		UserIDResetPasskeyDelete:      core.NewOperation(client, "UserIDResetPasskeyDelete", "管理员重置用户Passkey | New API", "DELETE", "/api/user/{id}/reset_passkey", "/zh/docs/api/management/user-management/user-id-reset_passkey-delete"),
		UserIDTwoFADelete:             core.NewOperation(client, "UserIDTwoFADelete", "管理员禁用用户2FA | New API", "DELETE", "/api/user/{id}/2fa", "/zh/docs/api/management/user-management/user-id-2fa-delete"),
		UserManagePost:                core.NewOperation(client, "UserManagePost", "管理用户状态 | New API", "POST", "/api/user/manage", "/zh/docs/api/management/user-management/user-manage-post"),
		UserModelsGet:                 core.NewOperation(client, "UserModelsGet", "获取用户可用模型 | New API", "GET", "/api/user/models", "/zh/docs/api/management/user-management/user-models-get"),
		UserPasskeyDelete:             core.NewOperation(client, "UserPasskeyDelete", "删除Passkey | New API", "DELETE", "/api/user/passkey", "/zh/docs/api/management/user-management/user-passkey-delete"),
		UserPasskeyGet:                core.NewOperation(client, "UserPasskeyGet", "获取Passkey状态 | New API", "GET", "/api/user/passkey", "/zh/docs/api/management/user-management/user-passkey-get"),
		UserPasskeyRegisterBeginPost:  core.NewOperation(client, "UserPasskeyRegisterBeginPost", "开始注册Passkey | New API", "POST", "/api/user/passkey/register/begin", "/zh/docs/api/management/user-management/user-passkey-register-begin-post"),
		UserPasskeyRegisterFinishPost: core.NewOperation(client, "UserPasskeyRegisterFinishPost", "完成注册Passkey | New API", "POST", "/api/user/passkey/register/finish", "/zh/docs/api/management/user-management/user-passkey-register-finish-post"),
		UserPasskeyVerifyBeginPost:    core.NewOperation(client, "UserPasskeyVerifyBeginPost", "开始验证Passkey | New API", "POST", "/api/user/passkey/verify/begin", "/zh/docs/api/management/user-management/user-passkey-verify-begin-post"),
		UserPasskeyVerifyFinishPost:   core.NewOperation(client, "UserPasskeyVerifyFinishPost", "完成验证Passkey | New API", "POST", "/api/user/passkey/verify/finish", "/zh/docs/api/management/user-management/user-passkey-verify-finish-post"),
		UserPost:                      core.NewOperation(client, "UserPost", "创建用户 | New API", "POST", "/api/user/", "/zh/docs/api/management/user-management/user-post"),
		UserPut:                       core.NewOperation(client, "UserPut", "更新用户 | New API", "PUT", "/api/user/", "/zh/docs/api/management/user-management/user-put"),
		UserSearchGet:                 core.NewOperation(client, "UserSearchGet", "搜索用户 | New API", "GET", "/api/user/search", "/zh/docs/api/management/user-management/user-search-get"),
		UserSelfDelete:                core.NewOperation(client, "UserSelfDelete", "注销当前用户 | New API", "DELETE", "/api/user/self", "/zh/docs/api/management/user-management/user-self-delete"),
		UserSelfGet:                   core.NewOperation(client, "UserSelfGet", "获取当前用户信息 | New API", "GET", "/api/user/self", "/zh/docs/api/management/user-management/user-self-get"),
		UserSelfGroupsGet:             core.NewOperation(client, "UserSelfGroupsGet", "获取当前用户分组 | New API", "GET", "/api/user/self/groups", "/zh/docs/api/management/user-management/user-self-groups-get"),
		UserSelfPut:                   core.NewOperation(client, "UserSelfPut", "更新当前用户信息 | New API", "PUT", "/api/user/self", "/zh/docs/api/management/user-management/user-self-put"),
		UserSettingPut:                core.NewOperation(client, "UserSettingPut", "更新用户设置 | New API", "PUT", "/api/user/setting", "/zh/docs/api/management/user-management/user-setting-put"),
		UserTokenGet:                  core.NewOperation(client, "UserTokenGet", "生成访问令牌 | New API", "GET", "/api/user/token", "/zh/docs/api/management/user-management/user-token-get"),
		UserTopupCompletePost:         core.NewOperation(client, "UserTopupCompletePost", "管理员完成充值 | New API", "POST", "/api/user/topup/complete", "/zh/docs/api/management/user-management/user-topup-complete-post"),
		UserTopupGet:                  core.NewOperation(client, "UserTopupGet", "获取所有充值记录 | New API", "GET", "/api/user/topup", "/zh/docs/api/management/user-management/user-topup-get"),
	}
}

type VendorsService struct {
	client           *core.Client
	VendorsGet       *core.Operation
	VendorsIDDelete  *core.Operation
	VendorsIDGet     *core.Operation
	VendorsPost      *core.Operation
	VendorsPut       *core.Operation
	VendorsSearchGet *core.Operation
}

func newVendorsService(client *core.Client) *VendorsService {
	return &VendorsService{
		client:           client,
		VendorsGet:       core.NewOperation(client, "VendorsGet", "获取所有供应商 | New API", "GET", "/api/vendors/", "/zh/docs/api/management/vendors/vendors-get"),
		VendorsIDDelete:  core.NewOperation(client, "VendorsIDDelete", "删除供应商 | New API", "DELETE", "/api/vendors/{id}", "/zh/docs/api/management/vendors/vendors-id-delete"),
		VendorsIDGet:     core.NewOperation(client, "VendorsIDGet", "获取指定供应商 | New API", "GET", "/api/vendors/{id}", "/zh/docs/api/management/vendors/vendors-id-get"),
		VendorsPost:      core.NewOperation(client, "VendorsPost", "创建供应商 | New API", "POST", "/api/vendors/", "/zh/docs/api/management/vendors/vendors-post"),
		VendorsPut:       core.NewOperation(client, "VendorsPut", "更新供应商 | New API", "PUT", "/api/vendors/", "/zh/docs/api/management/vendors/vendors-put"),
		VendorsSearchGet: core.NewOperation(client, "VendorsSearchGet", "搜索供应商 | New API", "GET", "/api/vendors/search", "/zh/docs/api/management/vendors/vendors-search-get"),
	}
}
